@extends('layouts.app')
@section('heading', 'Document Templates')
@section('content')
<div class="space-y-6">
    <div class="flex items-center justify-between">
        <p class="text-sm text-slate-400">Create reusable templates with variable placeholders for automated document generation.</p>
        @if(auth()->user()->isManager())
        <a href="{{ route('documents.create') }}" class="px-4 py-2 bg-brand-600 text-white rounded-lg text-sm font-medium hover:bg-brand-700 transition">+ New Template</a>
        @endif
    </div>

    {{-- Templates --}}
    <div class="bg-slate-900 rounded-xl border border-slate-800 overflow-hidden">
        <div class="px-5 py-3 border-b border-slate-800">
            <h3 class="text-sm font-semibold text-white">Templates</h3>
        </div>
        <table class="w-full text-sm">
            <thead><tr class="text-xs text-slate-500 uppercase tracking-wider border-b border-slate-800">
                <th class="text-left px-5 py-3">Name</th>
                <th class="text-left px-5 py-3">Type</th>
                <th class="text-left px-5 py-3">Variables</th>
                <th class="text-center px-5 py-3">Used</th>
                <th class="text-left px-5 py-3">Created By</th>
                <th class="px-5 py-3"></th>
            </tr></thead>
            <tbody>
            @forelse($templates as $t)
                <tr class="border-b border-slate-800/50 table-row">
                    <td class="px-5 py-3"><a href="{{ route('documents.show', $t) }}" class="text-brand-400 hover:text-brand-300 font-medium">{{ $t->name }}</a></td>
                    <td class="px-5 py-3"><span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-slate-800 text-slate-300">{{ ucfirst($t->type) }}</span></td>
                    <td class="px-5 py-3 text-slate-400">{{ $t->variables ? implode(', ', $t->variables) : '—' }}</td>
                    <td class="px-5 py-3 text-center text-slate-400">{{ $t->usage_count }}</td>
                    <td class="px-5 py-3 text-slate-400">{{ $t->createdBy?->name ?? '—' }}</td>
                    <td class="px-5 py-3 text-right">
                        <a href="{{ route('documents.show', $t) }}" class="text-xs text-slate-500 hover:text-slate-300">View</a>
                    </td>
                </tr>
            @empty
                <tr><td colspan="6" class="px-5 py-8 text-center text-slate-500">No templates yet. Create one to get started.</td></tr>
            @endforelse
            </tbody>
        </table>
        <div class="px-5 py-3">{{ $templates->links() }}</div>
    </div>

    {{-- Recently Generated --}}
    @if($generated->count())
    <div class="bg-slate-900 rounded-xl border border-slate-800 overflow-hidden">
        <div class="px-5 py-3 border-b border-slate-800">
            <h3 class="text-sm font-semibold text-white">Recently Generated</h3>
        </div>
        <table class="w-full text-sm">
            <thead><tr class="text-xs text-slate-500 uppercase tracking-wider border-b border-slate-800">
                <th class="text-left px-5 py-3">Document</th>
                <th class="text-left px-5 py-3">Template</th>
                <th class="text-left px-5 py-3">Project</th>
                <th class="text-left px-5 py-3">Generated By</th>
                <th class="text-left px-5 py-3">Date</th>
                <th class="px-5 py-3"></th>
            </tr></thead>
            <tbody>
            @foreach($generated as $g)
                <tr class="border-b border-slate-800/50 table-row">
                    <td class="px-5 py-3 text-slate-200 font-medium">{{ $g->title }}</td>
                    <td class="px-5 py-3 text-slate-400">{{ $g->template?->name ?? '—' }}</td>
                    <td class="px-5 py-3 text-slate-400">{{ $g->project?->name ?? '—' }}</td>
                    <td class="px-5 py-3 text-slate-400">{{ $g->generatedBy?->name ?? '—' }}</td>
                    <td class="px-5 py-3 text-slate-500">{{ $g->created_at->format('M j') }}</td>
                    <td class="px-5 py-3 text-right">
                        <a href="{{ route('documents.preview', $g) }}" class="text-xs text-brand-400 hover:text-brand-300">Preview</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    @endif
</div>
@endsection
